Added tests and serializers.
CjMonteclaro/Bookshelf pull request #1
Opened 2022-08-24 06:14 UTC by CjMonteclaro

2022-08-24 06:35 UTC, mikodagatan commented on app/models/list_item.rb
> +  validates :book_id, presence :true
`validates :book_id` is not needed as it's already defined in `belongs_to :book`

2022-08-24 06:35 UTC, mikodagatan commented on app/serializers/book_serializer.rb
> +  attributes :title, :author, :publisher, :synopsis, :cover_image_url, :pageCount
`pageCount` should be changed to `page_count`

2022-08-24 06:37 UTC, mikodagatan commented on app/models/user.rb
> +  validates :email, uniqueness: true
You can try adding `, format: { with: URI::MailTo::EMAIL_REGEXP }` to also validate the email format according to standards.

2022-08-24 06:39 UTC, mikodagatan commented on spec/factories.rb
> +    username {"test"}
Would really suggest putting a space in-between the value inside parentheses and the parentheses themselves. e.g. `{ "this is a string value" }` for better readability. 

It's best to learn to install rubocop in order to improve on this.

2022-08-24 06:42 UTC, mikodagatan commented on spec/factories.rb
> +    finish_date {Date.today + 1}
This one works, but it's better to be concise. `Date.current + 1.day`

Also, it would be better to use `Date.current` instead of today due to reasons like the one posted in this article

https://lottetreg.github.io/2019/12/27/date-today-vs-date-current-in-rails.html

2022-08-24 06:42 UTC, mikodagatan commented on spec/models/book_spec.rb
> +    @book1 = create(:book)
If we're assigning variables, it's better to use let

`let(:book1) { create(:book) }`

2022-08-24 06:47 UTC, mikodagatan commented on spec/request/list_item_request_spec.rb
> +    @list_item = create(:list_item)
If we're assigning variables outside of `it` blocks, it's better to use `let`

2022-08-24 06:48 UTC, mikodagatan commented on app/models/book.rb
>    has_many :users, through: :list_items, foreign_key: "owner_id"
Can we try using the symbol notation? `foreign_key: :owner_id`. I think it works that way and it's good for consistency.

2022-08-24 06:50 UTC, mikodagatan commented on app/models/book.rb
> +  validates :title, presence :true
I don't think this should work. Have you tried it out?

`validates :title, presence: true`

Here's the link that shows the first example to how it should be written, just for double-checking.https://guides.rubyonrails.org/active_record_validations.html

2022-08-24 06:51 UTC, mikodagatan commented on app/models/user.rb
>    has_many :books, through: :list_items, foreign_key: "owner_id"
Can you try using symbol notation on this one? `:owner_id`

2022-08-24 06:54 UTC, mikodagatan commented on spec/models/book_spec.rb
> +  it "is not valid without a title" do
It looks nice to have many examples on when 1 attribute is invalid. It seems to be a matter of preference, but for newer projects, I don't see much of the tests be like this.

2022-08-24 06:54 UTC, mikodagatan commented on spec/models/book_spec.rb
> +  it "is not valid without an pageCount" do
`pageCount` really is inconsistent. We'll really need to change it to `page_count`

2022-08-24 06:59 UTC, mikodagatan reviewed
@CjMonteclaro It is best to add description to your PRs as other people who will have to `context switch`

Try this description:

### Description
- Briefly write what's happening on the PR

### Reference
- Add reference as to why you're doing this PR. Usually these are tickets.

 ### Screenshots
 - If Applicable, for the front end, show screenshots of the changes done by this PR.

2022-08-24 07:00 UTC, mikodagatan requested changes
Looks good to me! Just a few comments.

2022-08-24 07:14 UTC, CjMonteclaro commented
Will resolve all the issues sir. Thank you for the comments!

2022-08-24 07:16 UTC, normancapule reviewed
Nice work! Left some additional comments / suggestions

2022-08-24 07:16 UTC, normancapule commented on spec/models/book_spec.rb
> +end
I think this is leftover code?

2022-08-24 07:16 UTC, normancapule commented on spec/factories.rb
> +    username {"test"}
consider using the faker gem https://github.com/faker-ruby/faker to automatically generate values here :)

2022-08-24 07:16 UTC, normancapule commented on spec/models/user_spec.rb
> +  end
same comment as @mikodagatan's, please use let to store variables. https://www.betterspecs.org/#let

2022-08-24 07:16 UTC, normancapule commented on spec/models/user_spec.rb
> +  end
I see this in your model

```
  validates :username, uniqueness: true
  validates :email, uniqueness: true
```

Where are your uniqueness tests?

2022-08-24 07:16 UTC, normancapule commented on spec/request/list_item_request_spec.rb
> +require 'rails_helper'
Since this is a request spec for an endpoint, some suggested changes:
1. Change the path of your spec. Each method in your controller is to be tested with a `success_spec` and optional `failure_spec`
```
/spec/requests/api/list_item_requests/index/success_spec
```

2. Change the RSpec.describe value:
```
RSpec.describe "GET /api/v1/list_item_requests", type: :request do
```

2022-08-24 07:16 UTC, normancapule commented on spec/request/list_item_request_spec.rb
> +RSpec.describe ListItem, type: :request do
Where is your authentication spec? What if the request is unauthorized?

2022-08-25 07:15 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +    before_action :authenticate_user!
It would be much better to put `before_action :authenticate_user!` in `ApplicationController` then just remove them on endpoints/action that don't need user auth.

to remove it on some of the controllers, you can use one of these:
`skip_before_action :authenticate_user!`
`before_action :authenticate_user!, except: %i[index create]` (just example)

2022-08-25 07:23 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +      render json: @list_items
Can you try using a `serializer` so that it will look like this? It doesn't seem like it's being used.

`render json: ListItemSerializer.new(@list_items).serialized_json, status: :ok` 

I think it should output data with a collection for list items instead. 

If it doesn't work with `FastJsonAPI` (I haven't used it), can you try the `blueprinter` gem?

2022-08-25 07:23 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +      render json: @list_items
same as above.

2022-08-25 07:23 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +      render json: @list_items
same as below

2022-08-25 07:23 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +      render json: @list_item
same as above

2022-08-25 07:24 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +        render json: @list_item.errors, status: :unprocessable_entity
You might want to make this

`json: { errors: @list_item.errors }` instead

2022-08-25 07:25 UTC, mikodagatan commented on app/controllers/api/list_items_controller.rb
> +        render json: @list_item.errors, status: :unprocessable_entity
You might want to make this

`json: { errors: @list_item.errors }, status: :unprocessable_entity` instead

2022-08-25 07:25 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +      render json: @users
PLease use the `UserSerializer`

2022-08-25 07:27 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +      render json: @user
same as above

2022-08-25 07:27 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +        render json: @user, status: :created, location: @user
same as above.

2022-08-25 07:28 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +        render json: @user.errors, status: :unprocessable_entity
same as above for the errors

2022-08-25 07:28 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +        render json: @user.errors, status: :unprocessable_entity
same as above for the errors

2022-08-25 07:28 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +        render json: @user
please use UserSerializer

2022-08-25 07:29 UTC, mikodagatan commented on app/controllers/users/registrations_controller.rb
> +        status: {code: 200, message: 'Signed up sucessfully.'},
Please remove the `status: {code: 200, message: 'Signed up sucessfully.'}` This is already inconsistent with the other controllers.

2022-08-25 07:29 UTC, mikodagatan commented on app/controllers/users/registrations_controller.rb
> +      }
add the status here or none at all, it defaults to `200` / `:ok`

2022-08-25 07:31 UTC, mikodagatan commented on app/controllers/users/sessions_controller.rb
> +# frozen_string_literal: true
It really would be better to remove `status: {code: 200, message: 'Logged in sucessfully.'}` You can move the `message` below `data:`

2022-08-25 07:35 UTC, mikodagatan commented on app/models/book.rb
>    has_many :list_items
Seems like we neeed to add `has_many :list_items, dependent: :destroy` so that we can avoid dangling data when we delete some of the records.

2022-08-25 07:35 UTC, mikodagatan commented on app/models/user.rb
>    has_many :list_items
Seems like we neeed to add `has_many :list_items, dependent: :destroy` so that we can avoid dangling data when we delete some of the records.

2022-08-25 07:36 UTC, mikodagatan commented on app/serializers/book_serializer.rb
> +class BookSerializer < ActiveModel::Serializer
Please use the serializer.

2022-08-25 07:36 UTC, mikodagatan commented on db/migrate/20220825063129_add_jti_to_users.rb
> +  add_index :users, :jti, unique: true
Please add a tab-space for this.

2022-08-25 07:38 UTC, mikodagatan commented on spec/factories.rb
> +end
Can you try enabling `Files: Insert Final Newline` on your vscode / other code editors?

![image](https://user-images.githubusercontent.com/22701608/186604466-457e2f43-57d7-4ac2-97a7-cbfb39eb1fd5.png)

2022-08-31 10:12 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +        render json: UserSerializer.new(@user).serialized_json, status: :created, location: @user
having `location: @user` in line with `render json:` and `status:` is inconsistent with the other renders and I don't think it's acceptable.

can you move it elsewhere?

2022-08-31 10:14 UTC, mikodagatan commented on app/controllers/users/registrations_controller.rb
> +        status: { message: "User couldn't be created successfully. #{resource.errors.full_messages.to_sentence }" }
This is still inconsistent with the other `render` lines. can you remove `status:` and move message outside of it?

line 14 shows `message:` in the first level in the hash.

2022-08-31 10:15 UTC, mikodagatan approved these changes
Looks a lot better to me! Thank you very much! There's still a few more comments though

2022-09-06 06:47 UTC, mikodagatan commented on app/controllers/api/books_controller.rb
> +      @book.destroy
Can you add a response for this one to confirm that it's destroyed? Thanks!

2022-09-06 06:48 UTC, mikodagatan commented on app/controllers/api/users_controller.rb
> +      @user.destroy
Add some responses here as well, thanks!

2022-09-06 06:49 UTC, mikodagatan approved these changes
Looks good to me

2022-09-06 06:56 UTC, merged